# Generated by Django 3.2.15 on 2022-09-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burgerplace', '0003_alter_menuitem_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='time_of_purchase',
            new_name='datetime_of_purchase',
        ),
    ]
