# Generated by Django 3.2.15 on 2022-09-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgerplace', '0004_rename_time_of_purchase_purchase_datetime_of_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
